#!/usr/bin/env bash

set -euo pipefail

function _generate() {
	cat <<- 'EOF'
		// Code generated by gen-doi.sh. DO NOT EDIT.
		//go:generate ./gen-doi.sh

		package trust

		var officialImagesRootKeys = []string{
	EOF

	while IFS= read -r line; do
		if [[ $line == \#* ]]; then
			printf '\t// %s\n' "${line/## /}"
		elif [[ -n $line ]]; then
			printf '\t"%s",\n' "$line"
		fi
	done < "doi-keys.txt"

	echo "}"
}

_generate | gofmt > doi_root_keys.go
